import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HeaderSlider from "../components/slider/HeaderSlider";
import SubSlider from "../components/film/filmSlider/SubSlider";
import { Divider } from "antd";

export default function Home({ darkMode, setDarkMode }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>TopFilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderSlider />
        <Divider orientation="left">The Most Top Films</Divider>
        <SubSlider />
      </main>
    </div>
  );
}
