import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HeaderSlider from "../components/slider/HeaderSlider";
import SubSlider from "../components/film/filmSlider/SubSlider";
import { Divider } from "antd";

const connectToDatabase = require("../util/mongodb");

export default function Home({ darkMode, setDarkMode, isConnected }) {
  console.log(isConnected, "is status of db");

  return (
    <div className={styles.container}>
      <Head>
        <title> Home | TopFilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderSlider />
        <Divider orientation="left">The Most Top Films</Divider>
        <SubSlider />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const client = await connectToDatabase();
  const isConnected = client.connections[0].readyState;
  return {
    props: {
      isConnected,
    },
  };
}
